# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ConsumoCredito' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConsumoCredito
  
  pod 'NVActivityIndicatorView'
  pod 'UICircularProgressRing'
  pod 'Alamofire', '~> 5.2'
  pod 'DTTextField'
  pod 'RNCryptor', '~> 5.0'
  pod 'FittedSheets'
  
  target 'ConsumoCreditoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConsumoCreditoUITests' do
    # Pods for testing
  end

end
